<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tewl\Tewl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TestFiles\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestFiles\TewlTestBook.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
